# Generated by Django 2.2 on 2021-06-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partyAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
    ]
